version: '3.8'

services:

  # Traefik Reverse Proxy
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./DAI-SSL:/etc/traefik/certificates 

  # Static Web Server with Nginx
  nginx:
    image: nginx:latest
    restart: always
    scale: 3
    volumes:
      - ./www:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`localhost`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.tls=true"
    expose:
      - "80"
  # Dynamic API Server with Javalin
  api:
    build:
      dockerfile: Dockerfile-api
    restart: always
    expose:
      - "7000"
    scale: 3
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api/`)"
     - "traefik.http.routers.api.service=api"
     - "traefik.http.routers.api.entrypoints=https"    
     - "traefik.http.routers.api.tls=true"
     - "traefik.http.services.api.loadbalancer.sticky=true" 

     - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
     - "traefik.http.middlewares.api.stripprefix.forceSlash=false"
     - "traefik.http.routers.api.middlewares=api-stripprefix"