version: '3.8'

services:
  # Static Web Server with Nginx
  nginx:
    image: nginx:latest
    container_name: static-web-server
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-web.rule=Host(`localhost`)"
      - "traefik.http.services.static-web.loadbalancer.server.port=80"

  # Dynamic API Server with Javalin
  api:
    image: your-image-name
    container_name: dynamic-api-server
    restart: always
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
     - "traefik.http.services.api.loadbalancer.server.port=7000"
     - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
     - "traefik.http.routers.api.middlewares=api-stripprefix"



  # Traefik Reverse Proxy
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
