version: '3.8'

services:
  # Static Web Server with Nginx
  nginx:
    image: nginx:latest
    restart: always
    scale: 3
    volumes:
      - ./www:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`localhost`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  # Dynamic API Server with Javalin
  api:
    build:
      dockerfile: Dockerfile-api
    restart: always
    scale: 3
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
     - "traefik.http.services.api.loadbalancer.server.port=7000"

     - "traefik.http.routers.api.entrypoints=https"
     - "traefik.http.routers.api.tls=true"
     - "traefik.http.routers.api.tls.certresolver=myresolver"
     
     - "traefik.http.services.api.loadbalancer.sticky=true" 

     - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
     - "traefik.http.routers.api.middlewares=api-stripprefix"



  # Traefik Reverse Proxy
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.https.http.tls=true"
      - "--entrypoints.https.http.tls.certresolver=myresolver"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./DAI-SSL:/etc/traefik/certificates 