providers:
  docker:
    exposedByDefault: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

api:
  insecure: true

tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305

  certificates:
    - certFile: "DAI-SSL/localhost.crt"
      keyFile: "DAI-SSL/localhost.key"
      
certificatesResolvers:
  myresolver:
    acme:
        email: romain.fleury@heig-vd.ch
        storage: /etc/traefik/certificates
        caServer: "https://acme-v02.api.letsencrypt.org/directory"
        httpChallenge:
            entryPoint: http